In [ ]:
# First import the necessary libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)

In [ ]:
# Next, read the differentcsv files into pandas dataframes 
df1 = pd.read_csv("clean_final_data.csv")

In [8]:
df2 = pd.read_csv("customers.csv")

In [9]:
df3 = pd.read_csv("orders.csv")

In [10]:
df4 = pd.read_csv("payments.csv")

In [11]:
df5 = pd.read_csv("products.csv")

In [12]:
df = pd.concat([df1, df2, df3, df4, df5], axis=1)

In [15]:
# Display the dataframe
df

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,OrderValue,CustomerID,Age,City,SignupDate,CustomerSegment,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,PaymentID,OrderID,PaymentDate,PaymentStatus,ProductID,ProductName,Category,UnitPrice
0,500001.0,103695.0,2025-08-28,2003.0,4.0,10.0,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,32.0,32.0,100001.0,22.0,Tehran,2023-09-11,Regular,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed,800001.0,500001.0,2025-08-28,Paid,2001.0,Wireless Mouse,Electronics,18.0
1,500002.0,107935.0,2024-05-31,2014.0,1.0,10.0,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,38.0,38.0,100002.0,55.0,Tabriz,2024-01-16,VIP,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed,800002.0,500002.0,2024-05-31,Paid,2002.0,Mechanical Keyboard,Electronics,62.0
2,500003.0,105141.0,2025-08-10,2002.0,1.0,20.0,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,50.0,50.0,100003.0,49.0,Karaj,2025-07-31,New,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed,800003.0,500003.0,2025-08-10,Paid,2003.0,USB-C Cable,Accessories,9.0
3,500004.0,108780.0,2024-10-11,2012.0,1.0,10.0,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,162.0,162.0,100004.0,39.0,Tehran,2023-04-23,New,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed,800004.0,500004.0,2024-10-11,Paid,2004.0,Power Bank,Electronics,35.0
4,500005.0,101187.0,2024-02-19,2008.0,2.0,0.0,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,28.0,28.0,100005.0,38.0,Tehran,2023-04-29,Regular,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed,800005.0,500005.0,2024-02-19,Paid,2005.0,Laptop Stand,Accessories,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
print("Rows, Columns:", df.shape)

Rows, Columns: (50120, 38)

In [17]:
# Column names, data types and how many non-empty values each column has
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50120 entries, 0 to 50119
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          49222 non-null  float64
 1   CustomerID       49222 non-null  float64
 2   OrderDate        49222 non-null  str
 3   ProductID        49222 non-null  float64
 4   Quantity         49222 non-null  float64
 5   Discount         49222 non-null  float64
 6   PaymentMethod    49222 non-null  str
 7   Status           49222 non-null  str
 8   Age              49222 non-null  float64
 9   City             49222 non-null  str
 10  SignupDate       49222 non-null  str
 11  CustomerSegment  49222 non-null  str
 12  ProductName      49222 non-null  str
 13  Category         49222 non-null  str
 14  UnitPrice        49222 non-null  float64
 15  Sales            49222 non-null  float64
 16  OrderValue       49222 non-null  float64
 17  CustomerID       10000 non-null  float64
 18  Age              9820 non-null   float64
 19  City             9881 non-null   str
 20  SignupDate       10000 non-null  str
 21  CustomerSegment  10000 non-null  str
 22  OrderID          50120 non-null  int64
 23  CustomerID       50120 non-null  int64
 24  OrderDate        50085 non-null  str
 25  ProductID        50120 non-null  int64
 26  Quantity         50040 non-null  float64
 27  Discount         49899 non-null  float64
 28  PaymentMethod    49668 non-null  str
 29  Status           50120 non-null  str
 30  PaymentID        50000 non-null  float64
 31  OrderID          50000 non-null  float64
 32  PaymentDate      49965 non-null  str
 33  PaymentStatus    50000 non-null  str
 34  ProductID        20 non-null     float64
 35  ProductName      20 non-null     str
 36  Category         20 non-null     str
 37  UnitPrice        20 non-null     float64
dtypes: float64(17), int64(3), str(18)
memory usage: 14.5 MB

In [18]:
df.describe()

,OrderID,CustomerID,ProductID,Quantity,Discount,Age,UnitPrice,Sales,OrderValue,CustomerID,Age,OrderID,CustomerID,ProductID,Quantity,Discount,PaymentID,OrderID,ProductID,UnitPrice
count,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,49222.000000,10000.00000,9820.000000,50120.000000,50120.000000,50120.000000,50040.000000,49899.000000,50000.000000,50000.000000,20.00000,20.000000
mean,525007.608366,105002.304356,2009.460160,1.881923,7.485576,41.283369,40.286579,69.985576,69.985576,105000.50000,41.321487,525003.244872,105543.821788,2009.458799,1.881455,0.075130,825000.500000,525000.500000,2010.50000,61.400000
std,14435.345449,2888.912895,5.578603,1.079382,7.754378,13.681355,42.613062,94.483273,94.483273,2886.89568,13.802441,14433.904231,22079.891005,5.577743,1.078846,0.077492,14433.901067,14433.901067,5.91608,62.836798
min,500001.000000,100001.000000,2001.000000,-2.000000,0.000000,18.000000,7.000000,-170.000000,-170.000000,100001.00000,18.000000,500001.000000,100001.000000,2001.000000,-2.000000,0.000000,800001.000000,500001.000000,2001.00000,7.000000
25%,512507.250000,102504.000000,2004.000000,1.000000,0.000000,29.000000,11.000000,17.000000,17.000000,102500.75000,29.000000,512503.750000,102515.000000,2004.000000,1.000000,0.000000,812500.750000,512500.750000,2005.75000,20.250000
50%,525016.500000,105005.000000,2008.000000,2.000000,5.000000,41.000000,28.000000,38.000000,38.000000,105000.50000,41.000000,525006.500000,105017.000000,2008.000000,2.000000,0.050000,825000.500000,525000.500000,2010.50000,45.000000
75%,537506.750000,107497.000000,2014.000000,2.000000,10.000000,53.000000,58.000000,84.000000,84.000000,107500.25000,53.000000,537501.250000,107510.000000,2014.000000,2.000000,0.100000,837500.250000,537500.250000,2015.25000,69.750000
max,550000.000000,110000.000000,2020.000000,5.000000,30.000000,65.000000,260.000000,1300.000000,1300.000000,110000.00000,65.000000,550000.000000,999999.000000,2020.000000,5.000000,0.300000,850000.000000,550000.000000,2020.00000,260.000000

In [19]:
# There are 50120 rows but Age has 49222 values and product id has 20.00000 some data is missing
df.isnull().sum()

OrderID              898
CustomerID           898
OrderDate            898
ProductID            898
Quantity             898
Discount             898
PaymentMethod        898
Status               898
Age                  898
City                 898
SignupDate           898
CustomerSegment      898
ProductName          898
Category             898
UnitPrice            898
Sales                898
OrderValue           898
CustomerID         40120
Age                40300
City               40239
SignupDate         40120
CustomerSegment    40120
OrderID                0
CustomerID             0
OrderDate             35
ProductID              0
Quantity              80
Discount             221
PaymentMethod        452
Status                 0
PaymentID            120
OrderID              120
PaymentDate          155
PaymentStatus        120
ProductID          50100
ProductName        50100
Category           50100
UnitPrice          50100
dtype: int64

In [ ]:
missing_values = (df.isnull().mean() * 100).round(1)
missing_values[missing_values > 0]